### ISSUE TITLE
Has been file template.yaml renamed to cfn-template.yaml?

### ISSUE THREAD

**Issue by satr** [awsdocs/aws-codestar-user-guide#2]
Hi,
I created a project for Alexa Skill (with Node.JS). Trying to find an instruction for renaming of Lambda function - [guideline reference to](https://docs.aws.amazon.com/codestar/latest/userguide/templates.html) `template.yaml`, but there is no such file - probably it is `cfn-template.yaml`?
```
You can modify or add an application resource, such as a Lambda function, 
in your runtime stack by editing the template.yml file in your project repository. 
```
Initial commit from CodeStart created project:

![image](https://user-images.githubusercontent.com/702860/50739430-71bbf280-11e0-11e9-9109-b54cef3c9309.png)

**Comment by macaller** [comment]
Hi Sergey--
I just tested this and I see the same file. I will verify that this is expected behavior, and if it is I will update the documentation.
