### ISSUE TITLE
Where is the source code for the codestar project templates? 

### ISSUE THREAD

**Issue by lestephane** [awsdocs/aws-codestar-user-guide#5]
I'd like to customize the Java Spring Web Service project template for another Web framework, and so would need to know where the source code for the project templates is.

The https://docs.aws.amazon.com/codestar/latest/userguide/cli-tutorial.html page mentions:

- [the sample application](https://docs.aws.amazon.com/codestar/latest/userguide/samples/nodews.zip) 
- [the sample toolchain](https://docs.aws.amazon.com/codestar/latest/userguide/samples/toolchain.zip)

That's about all I found in terms of publicly accessible codestar project templates.

Can you please put all of them on Github? Or if they already are, please point me to them.

Thank you

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
