### ISSUE TITLE
An Owner team member CANNOT ADD a user to a project from the Management Console

### ISSUE THREAD

**Issue by mariomerco** [awsdocs/aws-codestar-user-guide#8]
This documentation (https://docs.aws.amazon.com/codestar/latest/userguide/how-to-add-team-member.html) says: 

```If you have the owner role in an AWS CodeStar project or have the AWSCodeStarFullAccess policy applied to your IAM user, you can add other IAM users to the project team.```

But, when trying to do this from the **Management Console**, it seems to be performing an `codestar:UpdateUserProfile`, which is not necessary for what we are trying to achieve. This action is explicitly allowed **but** if the user is _itself_.

<img width="817" alt="image" src="https://user-images.githubusercontent.com/7386479/175110143-a805697a-1c80-45ef-9906-4fe59c545724.png">

The activity it should be doing really is `codestar:AssociateTeamMember` and `codestar:UpdateTeamMember`, which is completely valid and **works in with the AWS CLI**.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
